blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/dvelm/AI_Resume_Builder/discussions
    about: You can join the discussions on GitHub.
  - name: New issue
    url: >-
      https://github.com/dvelm/AI_Resume_Builder/blob/main/.github/CONTRIBUTING.md
    about: "Before opening a new issue, please make sure to read CONTRIBUTING.md"
